version: "3.8"

services:
  wordpress:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: betq48v2oh5xszipp7dv-mysql.services.clever-cloud.com:3306
      WORDPRESS_DB_USER: uqxqaoieqngk6grk
      WORDPRESS_DB_PASSWORD: mjcYz0bZg0xPFZfHRMOb
      WORDPRESS_DB_NAME: betq48v2oh5xszipp7dv
    restart: always
